### ISSUE TITLE
uPort Email Verification Flow (WIP)

### ISSUE THREAD

**Issue by bdresser** [uport-project/uport-verify#1]
### Background

To bridge the gap between Web 2 & Web 3, we can issue uPort credentials that attest to ownership of a particular email address. This feature is the first piece of a larger application that will help bootstrap the ecosystem of decentralized identity data.

The project here is pretty simple. We'll need a front-end for the user to submit their email address and a server to send a selective disclosure request via email, then sign and send an attestation. We're starting with [an awesome email verification library](https://github.com/mi-xu/uport-verify-email) by @mi-xu that handles most of the server-side functionality necessary (thx Mike <3 )

### User Journey
- User loads the site and is prompted for their email address
- User enters email address, taps 'continue', lands on a success screen
- User receives an email with a QR code
- User scans the QR code from email, shares device ID and uPort ID with the app
- User is pushed an attestation from the app that states they own the provided email address.

### Backend Requirements / Functionality
1. Receive an email address from frontend, and send a [selective disclosure QR](https://github.com/uport-project/specs/blob/develop/messages/sharereq.md) to received email. This is handled by the email verification library [here](https://github.com/mi-xu/uport-verify-email/blob/master/src/index.js#L96 ). The callback for the selective disclosure request can be something like `https://api.uport.me/verify`.
2. Receive callback from selective disclosure, parse verified email address, create & sign attestation saying MNID owns that email, and push attestation to user's device. This is also handled by the library [here](https://github.com/mi-xu/uport-verify-email/blob/master/src/index.js#L121). 

A couple notes: 
- the lib contains a `createUser()` function to create a record in a database, but this is unnecessary here – it was built for another use-case
- our team is a big fan of serverless infrastructure which may make sense for this project too
- you will need to create a uPort App Identity using the [app-manager](http://appmanager.uport.me/). you should use the application you register for testing, but in the final code please use an `ENV` variable for the `SimpleSigner` object used to declare your instance of the app.

### Frontend Requirements
1. Splash screen with a form field that validates on email address (perhaps with a simple Redux form) and sends valid emails to the backend
2. "Success" screen after the user submits an email address
3. Responsiveness for any browser size
4. Consistency with the below designs & branding guidelines

Design Requirements
- typeface should be [Nunito Sans](https://fonts.google.com/specimen/Nunito+Sans) 
- purple is `#5c50ca`

<img width="730" alt="screen shot 2018-04-12 at 1 13 37 pm" src="https://user-images.githubusercontent.com/1016190/38701725-8d06df5c-3e53-11e8-87f6-ffd31d71ef68.png">

<img width="947" alt="screen shot 2018-04-12 at 1 37 33 pm" src="https://user-images.githubusercontent.com/1016190/38702916-b5d5f3d4-3e56-11e8-898c-95784297b3bd.png">

**Comment by vs77bb** [comment]
Hi @bakoah I believe this issue was claimed on Gitcoin (worth 0.6 ETH). Will you please comment with your strategy and timeline for completion here? Hope you are doing well!

**Comment by bakaoh** [comment]
i'm working on this bounty, it's almost done https://github.com/bakaoh/uport-email-verification, 
but i got some problem with uport mobile app, it's takes forever to confirm so i can not create a real uport app to test
i'm still figuring it out some way to create an app through uport-cli but it took more time than i expected

**Comment by mkosowsk** [comment]
@bakaoh is it throwing any errors that could be of use? thanks!

@KamesCG could you provide some guidance on this when you get some cycles? 👍🏻

**Comment by KamesCG** [comment]
Wow - I'm loving the speed and focus on this.

@bakaoh uPort was specifically experiencing registration issues yesterday due to a `nonce` sync issue. If I'm understanding correctly you are unable to create a new uPort identity and therefore can't test? Can you timestamp exactly when you were attempting this? Would you mind trying one more time?

Also the `uport-cli-client` is the next bounty target, so if you're interested in improving the uPort developer experience via the CLI that will have a list of bounty candidates too.

thanks for the ping @mkosowsk

**Comment by bakaoh** [comment]
@KamesCG - thank you so much, it's exactly as you said, i was unable to create a new identify. I attempted all day yesterday with no luck, but after reinstall the app, it works like a charm (before reinstalling, i try one more time but it didn't work neither)

**Comment by bakaoh** [comment]
i have submitted the work and deploy test page here http://bakaoh.github.io/uport-email-verification
please review and let me know if there anything need to change

**Comment by mkosowsk** [comment]
@bakaoh wow, impressive turn-around time!

@KamesCG I tested and confirmed functionality but did not do a deep-dive on responsiveness or code review, unfortunately running a bit light on cycles at the moment

**Comment by bdresser** [comment]
@bakaoh this looks great! front-end is looking sharp, and thanks for the quick turnaround.

when i scan the request in my email, i am also sending along permission for push notifications. but i only receive the attestation via email, rather than via push notification.

looks like here https://github.com/mi-xu/uport-verify-email/blob/master/src/index.js#L141 the library should try to push if the user allows it. any idea why it's coming via email only? 

another note (on the library) is that the "If on mobile..." link should encode a deeplink URL rather than the QR code so that the user can complete the flow on mobile. Opened an issue [here](https://github.com/mi-xu/uport-verify-email/issues/3) on the lib itself – out of scope for this project.

cc @KamesCG

**Comment by bakaoh** [comment]
@bdresser what os do you use? i use uport app on android 7.0 and after scan request in email, the app receive notification and open the dialog to accept, since the app was till running foreground, i didn't see the notify on status bar (few time i close app fast enough / or the notify got delay, i do see the notify on status bar)

**Comment by bdresser** [comment]
awesome, thank you @bakaoh ! that PR should fix what i'm describing with the deep-link / QR

what do you mean the deeplinks behave differently? i'm on iOS 11, for me the `me.uport:me` link won't open the app but the `id.uport.me` link will.

i'm not receiving the push on iOS, but have confirmed with @KamesCG that the android flow receives both the push and the email. will have a couple more people test it out to see what's up here.

I'm noticing a CORS error on Safari 11 (screenshot below) and am also unable to complete the flow on iOS Safari or Chrome. 

<img width="582" alt="screen shot 2018-04-19 at 3 06 30 pm" src="https://user-images.githubusercontent.com/1016190/39020888-4fb0b066-43e3-11e8-9dd7-43534caf0bf5.png">

**Comment by bakaoh** [comment]
@bdresser -- i fixed the cors problem

> what do you mean the deeplinks behave differently? i'm on iOS 11, for me the me.uport:me link won't open the app but the id.uport.me link will.

when i open the app and scan qr code (which contain uri me.uport:me) the app open login dialog, and after click accept, a dialog popup and dismiss very fast, every after work as expected
when i open the mail in mobile and click the deeplink, the app open and show the login dialog, but after click accept here, a browser popup, open the callback url (the /verify endpoint) with a different format (access_token sent after the hash # instead of url query)

**Comment by bdresser** [comment]
ah, the funniness with the deeplinks is an issue with the android app.

i have released the bounty, thank you for your help @bakaoh !

**Comment by bakaoh** [comment]
thank you @bdresser
